import numpy as np

from pricer.products import call_payoff, put_payoff


def simulate_terminal_prices(S0, T, r, sigma, n_paths=100_000, seed=23):
    """Draw S_T under the risk-neutral Black-Scholes model."""
    rng = np.random.default_rng(seed)
    Z = rng.standard_normal(n_paths) # tirages de n_paths v.a normales centrées réduites
    return S0 * np.exp((r - 0.5 * sigma**2) * T + sigma * np.sqrt(T) * Z)

def mc_price(payoff_fn, S0, T, r, sigma, n_paths=100_000, seed=42):
    """Price any payoff that depends on S_T only, with its standard error."""
    ST = simulate_terminal_prices(S0, T, r, sigma, n_paths, seed)
    discounted = np.exp(-r * T) * payoff_fn(ST)
    return discounted.mean(), discounted.std(ddof=1) / np.sqrt(n_paths) # ddof pour le n-1 et pas n : sem = sqrt(1/(n-1) * sum((x_i - x_bar)^2))/sqrt(n)


def mc_call(S0, K, T, r, sigma, n_paths=100_000, seed=23):
    # mc_price strictly requires a payoff function with ONE argument (ST).
    # We use a lambda to create an anonymous wrapper function on the fly:
    # it catches the 'ST' array generated by mc_price, injects the fixed 'K',
    # and forwards both to our real call_payoff(ST, K) function.
    return mc_price(lambda ST: call_payoff(ST, K), S0, T, r, sigma, n_paths, seed) 

def mc_put(S0, K, T, r, sigma, n_paths=100_000, seed=42):
    # same logic
    return mc_price(lambda ST: put_payoff(ST, K), S0, T, r, sigma, n_paths, seed)